Resolve ducati_db job via DNS name, yay consul
[#116568637]

Signed-off-by: Gabe Rosenhouse <grosenhouse@pivotal.io>

diff --git a/jobs/acceptance-tests/templates/test.sh.erb b/jobs/acceptance-tests/templates/test.sh.erb
--- a/jobs/acceptance-tests/templates/test.sh.erb
+++ b/jobs/acceptance-tests/templates/test.sh.erb
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+set -eu
 
 export GOROOT=$(readlink -nf /var/vcap/packages/golang)
 
@@ -9,6 +10,14 @@ export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
 
 export GARDEN_SERVER_1="<%= p('ducati.acceptance_tests.garden_server_1') %>"
 export GARDEN_SERVER_2="<%= p('ducati.acceptance_tests.garden_server_2') %>"
+
+for i in {1..5}; do
+    ping -c1 ${GARDEN_SERVER_1} >/dev/null 2>&1 && break || sleep 5
+    if [ $i -eq 5 ]; then
+        echo "Unable to reach ${GARDEN_SERVER_1}..."
+        exit 1
+    fi
+done
 
 cd src/acceptance
 ginkgo -r
